repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.1"
    hooks:
      - id: codespell
        args: ["-I", "codespell.txt"]

ci:
  autoupdate_schedule: monthly
